### ISSUE TITLE
Box api not working

### ISSUE THREAD

**Issue by dipakagile** [golchha21/BoxPHPAPI#26]
Before some days box API working fine but when I run any action like create a folder then I get a below-mentioned error.I Check my credentials it ok. still, it's not working

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Box_API::build_url(), 1 passed in C:\xampp\htdocs\BoxPHPAPI-master\library\BoxAPI.class.php on line 137 and exactly 3 expected in C:\xampp\htdocs\BoxPHPAPI-master\library\BoxAPI.class.php:269 Stack trace: #0 C:\xampp\htdocs\BoxPHPAPI-master\library\BoxAPI.class.php(137): Box_API->build_url('/folders') #1 C:\xampp\htdocs\BoxPHPAPI-master\example.php(12): Box_API->create_folder('Liability Forms', '0') #2 {main} thrown in C:\xampp\htdocs\BoxPHPAPI-master\library\BoxAPI.class.php on line 269

**Comment by dipakagile** [comment]
I got it. its PHP version issue. its working fine in 5.6.31 its not worknig properly in php 7.0 +
